VL-1998 -  Using mysql driver for pentaho service
velocitycareerlabs/credit-market-server pull request #48
Opened 2022-04-05 14:08 UTC by hiteshprajapati

https://velocitycareerlabs.atlassian.net/browse/VL-1998 

## Description

- Pentaho Service was using Drizzle driver and because of that few reports are not working. 
- Changing Pentaho Service to use mysql jdbc driver which is even use for Velocity upper environment.
- Changing local development environment also to use mysql jdbc driver instead of drizzle.

## Checklist

Please make sure these boxes are checked before submitting your pull request - thanks!

- [ ] Write the commit message as per https://github.com/apache/fineract/#pull-requests

- [ ] Acknowledge that we will not review PRs that are not passing the build _("green")_ - it is your responsibility to get a proposed PR to pass the build, not primarily the project's maintainers.

- [ ] Create/update unit or integration tests for verifying the changes made.

- [ ] Follow coding conventions at https://cwiki.apache.org/confluence/display/FINERACT/Coding+Conventions.

- [ ] Add required Swagger annotation and update API documentation at fineract-provider/src/main/resources/static/api-docs/apiLive.htm with details of any API changes

- [ ] Submission is not a "code dump".  (Large changes can be made "in repository" via a branch.  Ask on the developer mailing list for guidance, if required.)

FYI our guidelines for code reviews are at https://cwiki.apache.org/confluence/display/FINERACT/Code+Review+Guide.

2022-04-05 17:36 UTC, hagafrank requested changes
Please test transactions. For example, try to perform deposit/withdrawal and confirm that transaction dates are captured correctly. We've had this issue in the past when changing mysql drivers. If that issue exists, you could try mariadb connector.

2022-04-06 07:54 UTC, hiteshprajapati commented
> Please test transactions. For example, try to perform deposit/withdrawal and confirm that transaction dates are captured correctly. We've had this issue in the past when changing mysql drivers. If that issue exists, you could try mariadb connector.

@hagafrank : As we discussed, I perform the deposit/withdrawal and confirming that all dates are captured correctly.
Thanks, Hitesh

2022-04-06 09:00 UTC, MageziArthur approved these changes
Looks good

2022-04-06 11:39 UTC, ItayPodhajcer approved these changes

2022-04-07 06:38 UTC, merged